from enum import StrEnum


class EmergencyState(StrEnum):
    REGISTRADA = "REGISTRADA"
    PRIORIZADA = "PRIORIZADA"
    PUBLICADA = "PUBLICADA"
    EN_PROCESO_ASIGNACION = "EN_PROCESO_ASIGNACION"
    ASIGNADA = "ASIGNADA"
    SIN_UNIDAD_DISPONIBLE = "SIN_UNIDAD_DISPONIBLE"
    EN_ATENCION = "EN_ATENCION"
    FALLO_DETECTADO = "FALLO_DETECTADO"
    REASIGNACION_PENDIENTE = "REASIGNACION_PENDIENTE"
    REASIGNADA = "REASIGNADA"
    CERRADA = "CERRADA"


class AmbulanceState(StrEnum):
    DISPONIBLE = "DISPONIBLE"
    CANDIDATA = "CANDIDATA"
    INTENTANDO_ACEPTAR = "INTENTANDO_ACEPTAR"
    ASIGNADA = "ASIGNADA"
    EN_ATENCION = "EN_ATENCION"
    INACTIVA = "INACTIVA"
    RECUPERADA = "RECUPERADA"


class AssignmentState(StrEnum):
    PENDIENTE = "PENDIENTE"
    CONFIRMADA = "CONFIRMADA"
    RECHAZADA = "RECHAZADA"
    FINALIZADA = "FINALIZADA"
    REASIGNADA = "REASIGNADA"


class FailureRecoveryState(StrEnum):
    DETECTADO = "DETECTADO"
    RECUPERADO = "RECUPERADO"


class EventType(StrEnum):
    EMERGENCY_CREATED = "EMERGENCY_CREATED"
    EMERGENCY_PRIORITIZED = "EMERGENCY_PRIORITIZED"
    EMERGENCY_PUBLISHED = "EMERGENCY_PUBLISHED"
    AMBULANCE_REGISTERED = "AMBULANCE_REGISTERED"
    HEARTBEAT_RECEIVED = "HEARTBEAT_RECEIVED"
    ASSIGNMENT_ATTEMPTED = "ASSIGNMENT_ATTEMPTED"
    ASSIGNMENT_CONFIRMED = "ASSIGNMENT_CONFIRMED"
    ASSIGNMENT_REJECTED = "ASSIGNMENT_REJECTED"
    NODE_FAILED = "NODE_FAILED"
    NODE_RECOVERED = "NODE_RECOVERED"
    REASSIGNMENT_STARTED = "REASSIGNMENT_STARTED"
    REASSIGNMENT_CONFIRMED = "REASSIGNMENT_CONFIRMED"
